apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/wussh/jenkins-flux-cicd.git
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: releases
  namespace: flux-system
spec:
  interval: 5m
  path: "./releases/azure"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repo
  wait: true
  timeout: 3m