# 1. Gateway HTTPS utama untuk Kubeflow
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kubeflow-gateway
  namespace: istio-system
spec:
  selector:
    istio: istio-gateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: kubeflow-tls
      hosts:
        - "kubeflow.wush.site"
---
# 2. VirtualService utama untuk Kubeflow
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubeflow
  namespace: istio-system
spec:
  gateways:
    - kubeflow-gateway
  hosts:
    - "kubeflow.wush.site"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: istio-gateway.istio-system.svc.cluster.local
            port:
              number: 80
---
# 3. ClusterIssuer untuk Let's Encrypt
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: andrianta.321@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: istio
---
# 4. Certificate Request untuk kubeflow.wush.site
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-cert
  namespace: istio-system
spec:
  secretName: kubeflow-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubeflow.wush.site
  dnsNames:
    - kubeflow.wush.site
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: acme-gateway
  namespace: istio-system
spec:
  selector:
    istio: istio-gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "kubeflow.wush.site"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: acme-challenge
  namespace: istio-system
spec:
  hosts:
    - "kubeflow.wush.site"
  gateways:
    - acme-gateway
  http:
    - match:
        - uri:
            prefix: "/.well-known/acme-challenge/"
      route:
        - destination:
            host: cm-acme-http-solver.istio-system.svc.cluster.local
            port:
              number: 8089
