apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kubeflow-gateway
  namespace: istio-system
spec:
  selector:
    istio: istio-gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "kubeflow.wush.site"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubeflow
  namespace: istio-system
spec:
  gateways:
    - kubeflow-gateway
  hosts:
    - "kubeflow.wush.site"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: istio-gateway.istio-system.svc.cluster.local
            port:
              number: 80